# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Gillian Sibthorpe – Digital Project Manager
email: gillianjacqueline@gmail.com
description: Digital Project Manager, Certified Scrum Master
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://gilliansibthorpe.com" # the base hostname & protocol for your site
twitter: GillSibthorpe
github:  GillSibthorpe
linkedin: gillian-sibthorpe-105ab6a7
picture: 'assets/photo-me.jpg'

# Some other stuff you can define if you fancy a play
# https://github.com/jekyll/jekyll-seo-tag
# analytics-google: 'UA-CODE-HERE-GILL'


# Build settings & some custom stuff.
markdown: kramdown
exclude: [README.md, Rakefile]
permalink: /blog/:year/:month/:day/:title
permalink: /404.html
sass:
  style: compressed

# Other useful stuff, emoji obv.
gems:
  - jekyll-sitemap
  - jemoji
  - jekyll-seo-tag
